name: Generate terraform docs

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Render terraform docs and fail on diff
        uses: step-security/terraform-docs-action@43f977ff483b4dcf2d1c13fce93bfc30b1164bd9 # v1.4.4
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"
      - name: Dump README
        if: failure()
        run: |
          cat README.md
