name: Tests
on:
  pull_request_target:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
        - 'static'

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge

    - uses: actions/setup-go@v5
      with:
        go-version: '1.18'

    - uses: chainguard-dev/actions/setup-registry@main
      with:
        port: 5000

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.3.*'
        terraform_wrapper: false

    - working-directory: ./examples/${{ matrix.example }}
      run: |
        export TF_VAR_target_repository=localhost:5000/${{ matrix.example }}
        terraform init -upgrade
        terraform apply -auto-approve
