name: Tests
on:
  pull_request_target:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
        - 'static'

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - uses: chainguard-dev/actions/setup-registry@main
      with:
        port: 5000

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.8.*'
        terraform_wrapper: false

    - working-directory: ./examples/${{ matrix.example }}
      env:
        TF_VAR_target_repository: localhost:5000/${{ matrix.example }}
      run: |
        terraform init -upgrade
        terraform apply -auto-approve

    # Test with archs and check_sbom=false
    - working-directory: ./examples/${{ matrix.example }}
      env:
        TF_VAR_target_repository: localhost:5000/${{ matrix.example }}
        TF_VAR_archs: '["x86_64"]'
        TF_VAR_check_sbom: 'false'
      run: |
        terraform init -upgrade
        terraform apply -auto-approve
